### ISSUE TITLE
Update to google-api-client 0.9.x

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/browse-everything#131]
This is required for use with Rails 5, because google-api-client 0.8.7 was released which locks to `activesupport < 5`

Upgrade instructions are here: https://github.com/google/google-api-ruby-client/blob/master/MIGRATING.md

**Comment by atz** [comment]
Resolved by #134

**Comment by emanuil-tolev** [comment]
Not having this released blocks using sufia 7.2.0 with Rails 5, so would be very interested to see a new release esp. considering the code's in already :). This is a new instance so I'm keen to see if it can be upgraded before we add it loads of user data.

I'm not sure I can help that much with testing it though so it may be easier for whoever has already done it in the past to do it... The bit I can't see how to do is how do I get "sufia ~> 7.2.0", but with browse-everything "tip of master" rather than sufia's usual dependency "browse-everything ~> 0.10.3"?
